---
# defaults file for roles/ec2_instance_create

ec2_instance_create_type: t2.micro
ec2_instance_create_image: ami-4dd5522b
ec2_instance_create_count: 1
ec2_instance_create_vpc_id: subnet-caea7083
ec2_instance_create_key: aitac-automation-key
ec2_instance_create_secg: aitac-automation-sg
ec2_instance_create_region: ap-northeast-1
ec2_instance_create_assign_public_ip: yes
ec2_instance_create_tags:
  Name: work-instance
  automation_group: work-instance
ec2_instance_create_volumes:
  - device_name: /dev/sda1
    volume_type: gp2
    volume_size: 10
    delete_on_termination: true
ec2_instance_create_inv_group_name: ec2_work-instance
ec2_instance_create_ansible_ssh_user: centos
ec2_instance_create_ansible_ssh_private_key_file: aitac-automation-key.pem
